---
mail:
  port: 465
  service: gmail

sqs:
  queue:
    aws:
      queueUrl: http://localhost:4576/queue/appquarium-pipeline-test-salesforce-worker.fifo
      credentials:
        endpoint: "http://localhost:4576"
        accessKeyId: abc
        secretAccessKey: abc
        region: us-east-1