---
sqs:
  queue:
    aws:
      queueUrl: http://localstack:4576/queue/iron_queue
      credentials:
        endpoint: "http://localstack:4576"
        accessKeyId: abc
        secretAccessKey: abc
        region: us-east-1
mail:
  host: smtp
  port: 2525
  secure: false
  ignoreTLS: true
mysql:
  host: mysql
  database: appquarium
  user: it_user
  password: user1234
  connectionLimit: 5
